export const movieData = [
  {
    score: 0.65095156,
    show: {
      id: 54660,
      url: 'https://www.tvmaze.com/shows/54660/movie-stars',
      name: 'Movie Stars',
      type: 'Scripted',
      language: 'English',
      genres: [],
      status: 'Ended',
      runtime: 30,
      averageRuntime: 30,
      premiered: '1999-07-11',
      ended: '2000-06-18',
      officialSite: null,
      schedule: {time: '', days: []},
      rating: {average: null},
      weight: 19,
      network: {
        id: 71,
        name: 'The WB',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: 70367, imdb: 'tt0182617'},
      image: null,
      summary:
        '<p>The life of a Hollywood couple raising their family in Malibu</p>',
      updated: 1630008082,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/54660'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/2068289'},
      },
    },
  },
  {
    score: 0.6081165,
    show: {
      id: 9369,
      url: 'https://www.tvmaze.com/shows/9369/movie-talk',
      name: 'Movie Talk',
      type: 'Variety',
      language: 'English',
      genres: [],
      status: 'Ended',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2015-12-05',
      ended: '2016-01-23',
      officialSite: 'http://www.londonlive.co.uk/programmes/movie-talk',
      schedule: {time: '17:30', days: ['Saturday']},
      rating: {average: null},
      weight: 11,
      network: {
        id: 391,
        name: 'London Live',
        country: {
          name: 'United Kingdom',
          code: 'GB',
          timezone: 'Europe/London',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: null, imdb: null},
      image: null,
      summary: '<p>A catch-up with a famous movie actor or director.</p>',
      updated: 1628465709,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/9369'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/575172'},
      },
    },
  },
  {
    score: 0.5991436,
    show: {
      id: 31947,
      url: 'https://www.tvmaze.com/shows/31947/movie-connections',
      name: 'Movie Connections',
      type: 'Documentary',
      language: 'English',
      genres: [],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2007-09-10',
      ended: '2009-02-25',
      officialSite: 'http://www.bbc.co.uk/programmes/b00gw8w7',
      schedule: {time: '21:00', days: ['Wednesday']},
      rating: {average: null},
      weight: 0,
      network: {
        id: 12,
        name: 'BBC One',
        country: {
          name: 'United Kingdom',
          code: 'GB',
          timezone: 'Europe/London',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: 89291, imdb: null},
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/127/319502.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/127/319502.jpg',
      },
      summary: '<p>Documentary series looking at famous British films.</p>',
      updated: 1505523567,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/31947'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/1302128'},
      },
    },
  },
  {
    score: 0.58851624,
    show: {
      id: 28034,
      url: 'https://www.tvmaze.com/shows/28034/elviras-movie-macabre',
      name: "Elvira's Movie Macabre",
      type: 'Scripted',
      language: 'English',
      genres: ['Horror'],
      status: 'Ended',
      runtime: 120,
      averageRuntime: 120,
      premiered: '1981-09-26',
      ended: '2014-10-31',
      officialSite: 'https://www.elvira.com/',
      schedule: {time: '08:00', days: ['Saturday']},
      rating: {average: null},
      weight: 57,
      network: {
        id: 72,
        name: 'Syndication',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: 71433, imdb: null},
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/110/277382.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/110/277382.jpg',
      },
      summary:
        '<p>Elvira has been the longest running TV Horror movie host. Played by Cassandra Peterson the Vampyre lady in black presents the movies with off the wall comments about both the current movie and herself. WIth her sleek sexy Vampire look, she is known, loved and recognized by people the world over.</p>',
      updated: 1626238337,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/28034'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/1168455'},
      },
    },
  },
  {
    score: 0.56921256,
    show: {
      id: 51961,
      url: 'https://www.tvmaze.com/shows/51961/the-movie-show',
      name: 'The Movie Show',
      type: 'Variety',
      language: 'English',
      genres: ['Comedy'],
      status: 'Running',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2020-11-27',
      ended: null,
      officialSite: 'https://www.syfy.com/the-movie-show',
      schedule: {time: '23:00', days: ['Wednesday']},
      rating: {average: null},
      weight: 40,
      network: {
        id: 16,
        name: 'Syfy',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: null, imdb: null},
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/283/709325.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/283/709325.jpg',
      },
      summary:
        '<p>Taped deep in the heart of the entertainment capital of the world in Modesto, Calif., <b>The Movie Show</b> is hosted by polar opposites Deb and Wade, both of whom have nothing in common other than their shared love of movies and that they\'re puppets. Each week they\'ll dish out hot takes on upcoming blockbusters, as well as classic fan-favorites.</p><p>The show will feature exclusive deleted scenes and a star-studded line-up of interview guests, including Bruce the shark from "Jaws" and Steven King\'s laptop. Deb and Wade will also catch-up with everyone\'s favorite movie stars of yesteryear, such as the T-Rex from "Jurassic Park," Splinter from "Teenage Mutant Ninja Turtles" and many more.</p>',
      updated: 1612438948,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/51961'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/2023330'},
      },
    },
  },
  {
    score: 0.531729,
    show: {
      id: 23428,
      url: 'https://www.tvmaze.com/shows/23428/sky-movie-specials',
      name: 'Sky Movie Specials',
      type: 'Talk Show',
      language: 'English',
      genres: [],
      status: 'To Be Determined',
      runtime: 30,
      averageRuntime: 30,
      premiered: '2017-01-02',
      ended: null,
      officialSite: null,
      schedule: {time: '', days: ['Monday']},
      rating: {average: null},
      weight: 23,
      network: {
        id: 596,
        name: 'Sky Cinema Family',
        country: {
          name: 'United Kingdom',
          code: 'GB',
          timezone: 'Europe/London',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: null, imdb: null},
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/88/220017.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/88/220017.jpg',
      },
      summary: '<p>A look behind the scenes at the biggest movie releases.</p>',
      updated: 1591740792,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/23428'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/1035148'},
      },
    },
  },
  {
    score: 0.504161,
    show: {
      id: 35549,
      url: 'https://www.tvmaze.com/shows/35549/show-me-the-movie',
      name: 'Show Me the Movie!',
      type: 'Panel Show',
      language: 'English',
      genres: ['Comedy'],
      status: 'Ended',
      runtime: 60,
      averageRuntime: 58,
      premiered: '2018-03-22',
      ended: '2019-03-28',
      officialSite: 'https://tenplay.com.au/channel-ten/show-me-the-movie',
      schedule: {time: '19:30', days: ['Thursday']},
      rating: {average: null},
      weight: 35,
      network: {
        id: 149,
        name: 'Network 10',
        country: {name: 'Australia', code: 'AU', timezone: 'Australia/Sydney'},
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: 344656, imdb: 'tt8098384'},
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/150/375292.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/150/375292.jpg',
      },
      summary:
        '<p><b>Show Me the Movie!</b> features two competing teams captained by acclaimed actor Jane Harber and comedy star Joel Creasey.</p><p>Each week, host Rove McManus, Jane and Joel will be joined by a stellar cast of different actors, comedians and visiting international stars, who will do battle in a series of funny, irreverent and always entertaining rounds.</p>',
      updated: 1633694576,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/35549'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/1630919'},
      },
    },
  },
  {
    score: 0.50150347,
    show: {
      id: 36559,
      url: 'https://www.tvmaze.com/shows/36559/greatest-ever-movie-blunders',
      name: 'Greatest Ever Movie Blunders',
      type: 'Documentary',
      language: 'English',
      genres: [],
      status: 'To Be Determined',
      runtime: 60,
      averageRuntime: 60,
      premiered: '2018-05-02',
      ended: null,
      officialSite:
        'http://www.channel5.com/show/greatest-ever-movie-blunders/',
      schedule: {time: '21:00', days: ['Thursday']},
      rating: {average: null},
      weight: 28,
      network: {
        id: 553,
        name: '5STAR',
        country: {
          name: 'United Kingdom',
          code: 'GB',
          timezone: 'Europe/London',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: 362173, imdb: null},
      image: null,
      summary:
        "<p>A selection of cinema's most unbelievable - and unforgiveable - faux pas.</p>",
      updated: 1613063919,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/36559'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/2029902'},
      },
    },
  },
  {
    score: 0.49216568,
    show: {
      id: 35188,
      url: 'https://www.tvmaze.com/shows/35188/30-even-scarier-movie-moments',
      name: '30 Even Scarier Movie Moments',
      type: 'Documentary',
      language: 'English',
      genres: ['Horror'],
      status: 'Ended',
      runtime: 45,
      averageRuntime: 45,
      premiered: '2007-10-31',
      ended: '2007-10-31',
      officialSite: null,
      schedule: {time: '', days: ['Wednesday']},
      rating: {average: null},
      weight: 22,
      network: {
        id: 52,
        name: 'Bravo',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: 203251, imdb: 'tt0901160'},
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/375/937815.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/375/937815.jpg',
      },
      summary:
        "<p><b>30 Even Scarier Movie Moments</b> counts down 30 more of the most frightening scenes in horror cinema, or any other genre. This is also a two-part sequel to 100 Scariest Movie Moments. The list mostly consists of movies that didn't quite make the first list, or popular movies that had come out since.</p>",
      updated: 1636904436,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/35188'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/1420455'},
      },
    },
  },
  {
    score: 0.48252892,
    show: {
      id: 6737,
      url: 'https://www.tvmaze.com/shows/6737/mtv-movie-and-tv-awards',
      name: 'MTV Movie and TV Awards',
      type: 'Award Show',
      language: 'English',
      genres: [],
      status: 'Running',
      runtime: null,
      averageRuntime: 119,
      premiered: '1992-06-10',
      ended: null,
      officialSite: 'http://www.mtv.com/movie-and-tv-awards',
      schedule: {time: '', days: []},
      rating: {average: null},
      weight: 45,
      network: {
        id: 22,
        name: 'MTV',
        country: {
          name: 'United States',
          code: 'US',
          timezone: 'America/New_York',
        },
      },
      webChannel: null,
      dvdCountry: null,
      externals: {tvrage: null, thetvdb: 80203, imdb: null},
      image: {
        medium:
          'https://static.tvmaze.com/uploads/images/medium_portrait/110/275881.jpg',
        original:
          'https://static.tvmaze.com/uploads/images/original_untouched/110/275881.jpg',
      },
      summary:
        '<p>The <b>MTV Movie and TV Awards</b> (formally known as the "MTV Movie Awards") is a film and TV awards show presented annually on MTV. The nominees are decided by producers and executives at MTV. Winners are decided online by the general public.</p>',
      updated: 1620291485,
      _links: {
        self: {href: 'https://api.tvmaze.com/shows/6737'},
        previousepisode: {href: 'https://api.tvmaze.com/episodes/2046200'},
      },
    },
  },
];
